// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// QuotesColumns holds the columns for the "quotes" table.
	QuotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "quote", Type: field.TypeString, Nullable: true},
		{Name: "author", Type: field.TypeFloat32, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// QuotesTable holds the schema information for the "quotes" table.
	QuotesTable = &schema.Table{
		Name:       "quotes",
		Columns:    QuotesColumns,
		PrimaryKey: []*schema.Column{QuotesColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "tg_id", Type: field.TypeInt64, Unique: true},
		{Name: "username", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "surname", Type: field.TypeString},
		{Name: "email", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		QuotesTable,
		UsersTable,
	}
)

func init() {
}
