// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"team-manager/ent/predicate"
	"team-manager/ent/quote"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// QuoteQuery is the builder for querying Quote entities.
type QuoteQuery struct {
	config
	ctx        *QueryContext
	order      []quote.OrderOption
	inters     []Interceptor
	predicates []predicate.Quote
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the QuoteQuery builder.
func (qq *QuoteQuery) Where(ps ...predicate.Quote) *QuoteQuery {
	qq.predicates = append(qq.predicates, ps...)
	return qq
}

// Limit the number of records to be returned by this query.
func (qq *QuoteQuery) Limit(limit int) *QuoteQuery {
	qq.ctx.Limit = &limit
	return qq
}

// Offset to start from.
func (qq *QuoteQuery) Offset(offset int) *QuoteQuery {
	qq.ctx.Offset = &offset
	return qq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (qq *QuoteQuery) Unique(unique bool) *QuoteQuery {
	qq.ctx.Unique = &unique
	return qq
}

// Order specifies how the records should be ordered.
func (qq *QuoteQuery) Order(o ...quote.OrderOption) *QuoteQuery {
	qq.order = append(qq.order, o...)
	return qq
}

// First returns the first Quote entity from the query.
// Returns a *NotFoundError when no Quote was found.
func (qq *QuoteQuery) First(ctx context.Context) (*Quote, error) {
	nodes, err := qq.Limit(1).All(setContextOp(ctx, qq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{quote.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (qq *QuoteQuery) FirstX(ctx context.Context) *Quote {
	node, err := qq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Quote ID from the query.
// Returns a *NotFoundError when no Quote ID was found.
func (qq *QuoteQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = qq.Limit(1).IDs(setContextOp(ctx, qq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{quote.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (qq *QuoteQuery) FirstIDX(ctx context.Context) int64 {
	id, err := qq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Quote entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Quote entity is found.
// Returns a *NotFoundError when no Quote entities are found.
func (qq *QuoteQuery) Only(ctx context.Context) (*Quote, error) {
	nodes, err := qq.Limit(2).All(setContextOp(ctx, qq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{quote.Label}
	default:
		return nil, &NotSingularError{quote.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (qq *QuoteQuery) OnlyX(ctx context.Context) *Quote {
	node, err := qq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Quote ID in the query.
// Returns a *NotSingularError when more than one Quote ID is found.
// Returns a *NotFoundError when no entities are found.
func (qq *QuoteQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = qq.Limit(2).IDs(setContextOp(ctx, qq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{quote.Label}
	default:
		err = &NotSingularError{quote.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (qq *QuoteQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := qq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Quotes.
func (qq *QuoteQuery) All(ctx context.Context) ([]*Quote, error) {
	ctx = setContextOp(ctx, qq.ctx, "All")
	if err := qq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Quote, *QuoteQuery]()
	return withInterceptors[[]*Quote](ctx, qq, qr, qq.inters)
}

// AllX is like All, but panics if an error occurs.
func (qq *QuoteQuery) AllX(ctx context.Context) []*Quote {
	nodes, err := qq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Quote IDs.
func (qq *QuoteQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if qq.ctx.Unique == nil && qq.path != nil {
		qq.Unique(true)
	}
	ctx = setContextOp(ctx, qq.ctx, "IDs")
	if err = qq.Select(quote.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (qq *QuoteQuery) IDsX(ctx context.Context) []int64 {
	ids, err := qq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (qq *QuoteQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, qq.ctx, "Count")
	if err := qq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, qq, querierCount[*QuoteQuery](), qq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (qq *QuoteQuery) CountX(ctx context.Context) int {
	count, err := qq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (qq *QuoteQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, qq.ctx, "Exist")
	switch _, err := qq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (qq *QuoteQuery) ExistX(ctx context.Context) bool {
	exist, err := qq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the QuoteQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (qq *QuoteQuery) Clone() *QuoteQuery {
	if qq == nil {
		return nil
	}
	return &QuoteQuery{
		config:     qq.config,
		ctx:        qq.ctx.Clone(),
		order:      append([]quote.OrderOption{}, qq.order...),
		inters:     append([]Interceptor{}, qq.inters...),
		predicates: append([]predicate.Quote{}, qq.predicates...),
		// clone intermediate query.
		sql:  qq.sql.Clone(),
		path: qq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Quote string `json:"quote,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Quote.Query().
//		GroupBy(quote.FieldQuote).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (qq *QuoteQuery) GroupBy(field string, fields ...string) *QuoteGroupBy {
	qq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &QuoteGroupBy{build: qq}
	grbuild.flds = &qq.ctx.Fields
	grbuild.label = quote.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Quote string `json:"quote,omitempty"`
//	}
//
//	client.Quote.Query().
//		Select(quote.FieldQuote).
//		Scan(ctx, &v)
func (qq *QuoteQuery) Select(fields ...string) *QuoteSelect {
	qq.ctx.Fields = append(qq.ctx.Fields, fields...)
	sbuild := &QuoteSelect{QuoteQuery: qq}
	sbuild.label = quote.Label
	sbuild.flds, sbuild.scan = &qq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a QuoteSelect configured with the given aggregations.
func (qq *QuoteQuery) Aggregate(fns ...AggregateFunc) *QuoteSelect {
	return qq.Select().Aggregate(fns...)
}

func (qq *QuoteQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range qq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, qq); err != nil {
				return err
			}
		}
	}
	for _, f := range qq.ctx.Fields {
		if !quote.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if qq.path != nil {
		prev, err := qq.path(ctx)
		if err != nil {
			return err
		}
		qq.sql = prev
	}
	return nil
}

func (qq *QuoteQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Quote, error) {
	var (
		nodes = []*Quote{}
		_spec = qq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Quote).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Quote{config: qq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(qq.modifiers) > 0 {
		_spec.Modifiers = qq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, qq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (qq *QuoteQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := qq.querySpec()
	if len(qq.modifiers) > 0 {
		_spec.Modifiers = qq.modifiers
	}
	_spec.Node.Columns = qq.ctx.Fields
	if len(qq.ctx.Fields) > 0 {
		_spec.Unique = qq.ctx.Unique != nil && *qq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, qq.driver, _spec)
}

func (qq *QuoteQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(quote.Table, quote.Columns, sqlgraph.NewFieldSpec(quote.FieldID, field.TypeInt64))
	_spec.From = qq.sql
	if unique := qq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if qq.path != nil {
		_spec.Unique = true
	}
	if fields := qq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, quote.FieldID)
		for i := range fields {
			if fields[i] != quote.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := qq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := qq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := qq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := qq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (qq *QuoteQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(qq.driver.Dialect())
	t1 := builder.Table(quote.Table)
	columns := qq.ctx.Fields
	if len(columns) == 0 {
		columns = quote.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if qq.sql != nil {
		selector = qq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if qq.ctx.Unique != nil && *qq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range qq.modifiers {
		m(selector)
	}
	for _, p := range qq.predicates {
		p(selector)
	}
	for _, p := range qq.order {
		p(selector)
	}
	if offset := qq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := qq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (qq *QuoteQuery) Modify(modifiers ...func(s *sql.Selector)) *QuoteSelect {
	qq.modifiers = append(qq.modifiers, modifiers...)
	return qq.Select()
}

// QuoteGroupBy is the group-by builder for Quote entities.
type QuoteGroupBy struct {
	selector
	build *QuoteQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (qgb *QuoteGroupBy) Aggregate(fns ...AggregateFunc) *QuoteGroupBy {
	qgb.fns = append(qgb.fns, fns...)
	return qgb
}

// Scan applies the selector query and scans the result into the given value.
func (qgb *QuoteGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qgb.build.ctx, "GroupBy")
	if err := qgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuoteQuery, *QuoteGroupBy](ctx, qgb.build, qgb, qgb.build.inters, v)
}

func (qgb *QuoteGroupBy) sqlScan(ctx context.Context, root *QuoteQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(qgb.fns))
	for _, fn := range qgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*qgb.flds)+len(qgb.fns))
		for _, f := range *qgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*qgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// QuoteSelect is the builder for selecting fields of Quote entities.
type QuoteSelect struct {
	*QuoteQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (qs *QuoteSelect) Aggregate(fns ...AggregateFunc) *QuoteSelect {
	qs.fns = append(qs.fns, fns...)
	return qs
}

// Scan applies the selector query and scans the result into the given value.
func (qs *QuoteSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, qs.ctx, "Select")
	if err := qs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*QuoteQuery, *QuoteSelect](ctx, qs.QuoteQuery, qs, qs.inters, v)
}

func (qs *QuoteSelect) sqlScan(ctx context.Context, root *QuoteQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(qs.fns))
	for _, fn := range qs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*qs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := qs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (qs *QuoteSelect) Modify(modifiers ...func(s *sql.Selector)) *QuoteSelect {
	qs.modifiers = append(qs.modifiers, modifiers...)
	return qs
}
