// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"team-manager/ent/quote"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Quote is the model entity for the Quote schema.
type Quote struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Quote holds the value of the "quote" field.
	Quote string `json:"quote,omitempty"`
	// Author holds the value of the "author" field.
	Author *float32 `json:"author,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Quote) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case quote.FieldAuthor:
			values[i] = new(sql.NullFloat64)
		case quote.FieldID:
			values[i] = new(sql.NullInt64)
		case quote.FieldQuote:
			values[i] = new(sql.NullString)
		case quote.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Quote fields.
func (q *Quote) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case quote.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			q.ID = int64(value.Int64)
		case quote.FieldQuote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quote", values[i])
			} else if value.Valid {
				q.Quote = value.String
			}
		case quote.FieldAuthor:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field author", values[i])
			} else if value.Valid {
				q.Author = new(float32)
				*q.Author = float32(value.Float64)
			}
		case quote.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				q.CreatedAt = value.Time
			}
		default:
			q.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Quote.
// This includes values selected through modifiers, order, etc.
func (q *Quote) Value(name string) (ent.Value, error) {
	return q.selectValues.Get(name)
}

// Update returns a builder for updating this Quote.
// Note that you need to call Quote.Unwrap() before calling this method if this Quote
// was returned from a transaction, and the transaction was committed or rolled back.
func (q *Quote) Update() *QuoteUpdateOne {
	return NewQuoteClient(q.config).UpdateOne(q)
}

// Unwrap unwraps the Quote entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (q *Quote) Unwrap() *Quote {
	_tx, ok := q.config.driver.(*txDriver)
	if !ok {
		panic("ent: Quote is not a transactional entity")
	}
	q.config.driver = _tx.drv
	return q
}

// String implements the fmt.Stringer.
func (q *Quote) String() string {
	var builder strings.Builder
	builder.WriteString("Quote(")
	builder.WriteString(fmt.Sprintf("id=%v, ", q.ID))
	builder.WriteString("quote=")
	builder.WriteString(q.Quote)
	builder.WriteString(", ")
	if v := q.Author; v != nil {
		builder.WriteString("author=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(q.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Quotes is a parsable slice of Quote.
type Quotes []*Quote
