// Code generated by ent, DO NOT EDIT.

package ent

import (
	"team-manager/ent/quote"
	"team-manager/ent/schema"
	"team-manager/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	quoteFields := schema.Quote{}.Fields()
	_ = quoteFields
	// quoteDescCreatedAt is the schema descriptor for created_at field.
	quoteDescCreatedAt := quoteFields[3].Descriptor()
	// quote.DefaultCreatedAt holds the default value on creation for the created_at field.
	quote.DefaultCreatedAt = quoteDescCreatedAt.Default.(time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[7].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(time.Time)
}
