// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Quote is the predicate function for quote builders.
type Quote func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
